project: 
  type: website
  output-dir: docs

website: 
  title: Wstęp do kwantowego uczenia maszynowego
  sidebar:
    style: "docked" 
    contents:
      - index.qmd
      - info.qmd
      - section : "Wykłady"
        contents:
          - lectures/wyklad1.qmd
          - lectures/wyklad2.qmd
          - section : "ćwiczenia do W2"
            contents:
            - lectures/cw_w2.ipynb
          - lectures/wyklad3.qmd
          - lectures/wyklad4.qmd
          - lectures/wyklad5.qmd
          - section : "ćwiczenia do W5"
            contents:
            - lectures/cw_w5.ipynb
      - section: "Ćwiczenia"
        contents:
          - labs/cw1.ipynb
          - labs/cw2.ipynb
          - labs/cw3.ipynb
          - labs/cw4.ipynb
          - labs/cw5.ipynb
          - labs/cw6.ipynb
      # - section: "Ćwiczenia Qiskit"
      #   contents:
      #     - labs/Qiskit/cw1.ipynb
      #     - labs/Qiskit/cw2.ipynb
      #     - labs/Qiskit/cw3.ipynb
  navbar:
    left:
          - href: sylabus.qmd
            text: Sylabus
          - href: ksiazki.qmd
            text: Książki
          

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    self-contained-math: true