---
title: Literatura
---

## Książki 

<div id="QC">
### Obliczenia kwantowe (Quantum Computing)
</div>

1. C. Bernhardt, _Obliczenia kwantowe dla każdego_. PWN 2020

2. T. G. Wong, _Introduction to Classical and Quantum Computing_. Rooted Grove 2022.

3. P. Gawron, M. Cholewa, ... _Rewolucja stanu. Fantastyczne wprowadzenie do informatyki kwantowej_. Quantumz.io 2021

4. M. Le Bellac, _Wstęp do informatyki kwantowej_. PWN 2011

5. R. S. Sutor, _Dancing with Qubits_. Second edition, Packt 2024 

<div id="QML">
### Quantum Machine Learning
</div>
1.  M. Schuld, F. Petruccione, _Machine Learning with Quantum Computers_, Springer 2021.

2. A. Jacquier, O. Kondratyev, _Quantum Machine Learning and Optimisation in Finance. On the Road to Quantum Advantage_.

3. A. Saxena, J. Mancilla, I. Montalban, C. Pere, _Financial Modeling Using Quantum Computing_. Packt 2023


<div id="AI">
### AI 
</div>

1. A. Geron, _Uczenie maszynowe z użyciem Scikit-Learn i TensorFlow_. Helion 2024

2. S. Zajac, _Modelowanie dla biznesu, Analityka w czasie rzeczywistym - narzędzia informatyczne i biznesowe_. SGH 2022

3. L. Moroney, _Sztuczna inteligencja i uczenie maszynowe dla programistów. Praktyczny przewodnik po sztucznej inteligencji_. Helion 2021.
[Zobacz opis](http://helion.pl/view/111546/szinum.html) lub [Kup e-book](http://helion.pl/add111546~szinum_ebook)

4. Bruce, Bruce, Gedeck, _Statystyka praktyczna w data science. Wydanie II_. Helion. 2021.

## Strony WWW

1. Peter Shor [Wykład](https://math.mit.edu/~shor/435-LN/)

### Pakiety Python

1. [Qiskit](http://www.numpy.org)
2. [PennyLane](http://www.scipy.org)

### Edytory tekstu

1. [Visual Studio Code](https://code.visualstudio.com)
2. [Sublime Text](https://www.sublimetext.com)
3. [Notepad++](https://notepad-plus-plus.org/download)

### Markdown

1. [MD](http://daringfireball.net/projects/markdown/)

### Filmy

-  [Wprowadzenie do obliczeń kwantowych](https://www.youtube.com/watch?v=-UlxHPIEVqA)
-   QPoland, Bronze, [Warsztaty z programowania komputerów kwantowych 2023](https://www.youtube.com/watch?v=nDCROyWULkw&list=PLjZhz-aJHvA1q5DcsR_Y1XvsF2juz0FoN&index=2)

Wprowadzenie do Mechaniki Kwantowej

-	[Quantum Mechanics - Stanford Encyclopedia of Philosophy](https://plato.stanford.edu/entries/qt-interpret/)
-	[Introduction to Quantum Mechanics - Khan Academy](https://www.khanacademy.org/science/quantum-physics)

Podstawy Obliczeń Kwantowych

-	[Quantum Computing for Beginners - Microsoft Azure](https://docs.microsoft.com/en-us/azure/quantum/overview-quantum-computing)
-	[A Beginner’s Guide to Quantum Computing - IBM Quantum](https://www.ibm.com/quantum-computing/learn/what-is-quantum-computing/)


Wprowadzenie do Qubits i Algorytmów Kwantowych

-	[Qubits - What Are They and How Do They Work? - Qiskit](https://qiskit.org/textbook/ch-algorithms/what-are-qubits.html)
-	[Quantum Algorithms - Qiskit Textbook](https://qiskit.org/textbook/ch-algorithms/index.html)

Praktyczne Zastosowania i Rozwój Komputerów Kwantowych

-	[The State of Quantum Computing - IBM Research](https://www.ibm.com/blog/quantum-computing/)
-	[Google’s Quantum AI Research](https://quantumai.google/)

Dyskusje i Kursy Online

-    [Quantum Computing - Coursera](https://www.coursera.org/learn/quantum-computing)
-    [Quantum Mechanics and Quantum Computation - edX](https://www.edx.org/course/quantum-mechanics-and-quantum-computation)
