---
title: Sylabus
---

> Nazwa przedmiotu: {{< var main.nazwa >}}
> 
> Jednostka: {{< var main.uczelnia >}}
> 
> Kod przedmiotu: {{< var main.kod >}}, 232530-S
>
> Punkty ECTS: 3
>
> Język prowadzenia: polski
>
> Poziom przedmiotu: średnio-zaawansowany


**Prowadzący:** [Sebastian Zając](https://sebastianzajac.pl), 
  [sebastian.zajac@sgh.waw.pl](mailto:sebastian.zajac@sgh.waw.pl)


**Website:**
  [https://sebkaz-teaching.github.io/intro_to_qml/](https://sebkaz-teaching.github.io/intro_to_qml/)



## Cel Przedmiotu

Jeszcze do niedawna rozwój technologiczny oparty był na zmniejszaniu rozmiaru tranzystorów i zwiększaniu mocy obliczeniowej procesorów. 
Ze względu na fizyczne aspekty natury proces ten, od pewnego momentu, musi uwzględniać ograniczenia fizyki kwantowej. 
Przyszłość może jednak wykorzystać inne narzędzia, których możliwości wykraczają poza klasyczne moce obliczeniowe. 
Mimo, iż konstrukcja komputerów kwantowych to wciąż etap inżynierski, to okazuje się, że można już wskazać i wykorzystać je do tworzenia algorytmów, 
które można wykorzystać w dziedzinie uczenia maszynowego. 
Wykorzystanie algorytmów kwantowych pozwala zmniejszyć czas przetwarzania dużej ilości danych, a tym samym rozszerza możliwości 
przetwarzania i modelowania danych. Przedstawione na zajęciach biblioteki - IBM qiskit czy Pennylane (python) pozwalają na prostą
i szybką konstrukcje dowolnego algorytmu kwantowego. 
Algorytmy te, jak np. algorytm Grovera wykorzystać można do wielu problemów obliczeniowych uczenia
maszynowego bądź do konstrukcji kwantowych sieci neuronowych.

## Program przedmiotu

1. Komputery klasyczne i kwantowe
2. Klasyczne bramki logiczne - Algebra Boola
3. Przestrzenie wektorowe, stany kwantowe, reprezentacja klasycznych i kwantowych bitów
4. Kwantowe bramki logiczne w prostych algorytmach i obwodach kwantowych
5. Algorytmy kwantowego uczenia maszynowego
6. Biblioteka Qiskit, Pennylane wprowadzenie
7. Bramki jednokubitowe
8. Bramki wielokubitowe
9. Algorytm Deutscha, szyfrowanie kwantowe
10. Parametryzowane obwody kwantowe
11. Wariacyjne algorytmy kwantowe
12. Klasyfikacja binarna na przykładzie danych Titanic
13. QAOA - jako przykład wariacyjnego algorytmu
14. Kwantowe sieci neuronowe cz.1
15. kwantowe sieci neuronowe cz.2 


## Efekty kształcenia

1. Wiedza:

- Zna i rozumie koncepcje działania komputera klasycznego i kwantowego
- Zna metody kwantowego uczenia maszynowego możliwe do wykorzystania w biznesie
- Rozumie potrzebę i możliwości zastosowania komputerów kwantowych

2. Umiejętności:

- Potrafi stworzyć proste algorytmy z wykorzystaniem kwantowych bramek logicznych
- Umie wykorzystać biblioteki pythonowe do generowania kodów obliczeń kwantowych
- Potrafi wykorzystać metody nadzorowane wykorzystywane w kwantowym uczeniu maszynowym
- Potrafi wykorzystać metody nienadzorowane wykorzystywane w kwantowym uczeniu maszynowym
- Umie stworzyć prostą kwantową sieć neuronową

3. Kompetencje społeczne:

- formułuje problem biznesowy wraz z jego informatycznym rozwiązaniem
- uzupełniania wiedzę teoretyczną jak i praktyczną, w zakresie teorii, programowania, modelowania, nowych technologii informatycznych z wykorzystaniem kwantowego uczenia maszynowego

## Realizacja przedmiotu

- egzamin testowy: 40\%
- kolokwium: 20\%
- referaty/eseje: 40\%

## Literatura

1. S. Zajac - Modelowanie dla Biznesu. Analiza danych w czasie rzeczywistym. Oficyna Wydawnicza SGH. 2021
2. Cybulski, J.L., Zając, S. (2024). Design Considerations for Denoising Quantum Time Series Autoencoder. Computational Science – ICCS 2024. ICCS 2024. Lecture Notes in Computer Science, vol 14837. Springer, Cham. https://doi.org/10.1007/978-3-031-63778-0_18 
3. M. Schuld, F. Petruccione - Supervised Learning with Quantum Computers, Quantum Science and Technology. Springer 2018 https://doi.org/10.1007/978-3-319-96424-9
4. C. Bernhardt - Obliczenia kwantowe dla każdego, Wydawnictwo Naukowe PWN 2020
5. P. Gawron, M. Cholewa, ... _Rewolucja stanu. Fantastyczne wprowadzenie do informatyki kwantowej_. Quantumz.io 2021
6.  A. Saxena, J. Mancilla, I. Montalban, C. Pere, _Financial Modeling Using Quantum Computing_. Packt 2023
7. A. Jacquier, O. Kondratyev, _Quantum Machine Learning and Optimisation in Finance. On the Road to Quantum Advantage_.

## Literatura uzupełniająca

1. Michael A. Nielsen & Isaac L. Chuang - Quantum Computation and Quantum Information, Cambridge University Press, 2010
2. K. Przanowski, S. Zając - Modelowanie dla Biznesu. Metody Machine learning, Modele portfela consumer finance, modelek rekurencyjne analizy przeżycia, modele scoringowe. Oficyna Wydawnicza SGH. 2020
3. E. Frątczak - Modelowanie dla Biznesu. Regresja Logistyczna, Regresja Poissona, Survival Data Mining, CRM, Credit Scoring. Oficyna Wydawnicza SGH. 2019